[package]
name = "guana-service"
version = "0.1.0"
edition = "2021"

[dependencies]
guana-grpc-types = { path = "../guana-grpc-types" }

tonic-health = "0.9.2"
tonic = { version = "0.9.2" }
tracing = "0.1.37"